# --- R/index.R --------------------------------------------------------------
# build_run_index(run_dir, run_ts): writes <run_dir>/index.html - a SELF-CONTAINED
# viewer for THIS run only. The vertical menu is PROPORTIONAL to the executed
# sections (it scans run_dir for section folders that actually produced assets),
# and every asset path is RELATIVE to the run dir, so the run folder + its
# index.html are portable together. Called at the end of run_exhaustive.R (so the
# index is generated by the pipeline) and by the standalone build_index.R CLI.
#
# Horizontal tabs per section: Info & References | Options | Tabs (rendered from
# the section's metadata_ui markdown via commonmark) + Results (this run's assets).

build_run_index <- function(run_dir, run_ts, base = system.file("scaffold", package = "CorpusBiblioExtractor")) {
  if (!requireNamespace("commonmark", quietly = TRUE)) {
    message("[index] commonmark not available; skipping index.html"); return(invisible(NULL))
  }
  fwd     <- function(p) gsub("\\\\", "/", p)
  esc     <- function(s) { s <- gsub("&", "&amp;", s, fixed = TRUE); s <- gsub("<", "&lt;", s, fixed = TRUE); gsub(">", "&gt;", s, fixed = TRUE) }
  md2html <- function(path) {
    if (is.null(path) || !file.exists(path)) return(NULL)
    txt <- paste(readLines(path, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
    commonmark::markdown_html(txt, extensions = TRUE)
  }
  humanize <- function(id) {
    num  <- regmatches(id, regexpr("^[0-9.]+", id))
    rest <- tools::toTitleCase(gsub("_", " ", sub("^[0-9.]+_?", "", id)))
    list(num = num, title = rest)
  }
  sortkey <- function(num) {
    parts <- suppressWarnings(as.integer(strsplit(num, ".", fixed = TRUE)[[1]])); parts[is.na(parts)] <- 0L
    paste(sprintf("%04d", parts), collapse = ".")
  }

  # --- sections actually executed = run_dir subfolders that hold assets --------
  ran_ids <- list.dirs(run_dir, recursive = FALSE, full.names = FALSE)
  ran_ids <- ran_ids[!grepl("^_", ran_ids)]
  has_assets <- function(id) {
    fs <- list.files(file.path(run_dir, id), recursive = TRUE)
    any(!grepl("_files/", fs))
  }
  ran_ids <- ran_ids[vapply(ran_ids, has_assets, logical(1))]
  if (!length(ran_ids)) { message("[index] no executed sections in ", run_dir); return(invisible(NULL)) }

  # map section id -> scaffold dir (for metadata + group)
  all_dirs  <- fwd(list.dirs(base, recursive = TRUE, full.names = TRUE))
  leaf_dirs <- dirname(all_dirs[basename(all_dirs) == "metadata_ui"])
  scaffold  <- stats::setNames(leaf_dirs, basename(leaf_dirs))

  # Results HTML for one section: assets grouped by combination, paths RELATIVE
  # to the run dir (<id>/<combo>/<file>).
  results_html <- function(id) {
    sdir   <- file.path(run_dir, id)
    combos <- list.dirs(sdir, recursive = FALSE, full.names = FALSE)
    blocks <- character(0)
    for (cb in sort(combos)) {
      files <- list.files(file.path(sdir, cb)); files <- files[!grepl("_files$", files)]
      if (!length(files)) next
      items <- character(0)
      for (f in sort(files)) {
        rel <- paste0(id, "/", cb, "/", f)
        ext <- tolower(tools::file_ext(f))
        if (ext == "png")
          items <- c(items, sprintf('<figure class="asset"><img loading="lazy" src="%s" alt="%s"><figcaption>%s</figcaption></figure>', rel, esc(f), esc(f)))
        else {
          ico <- switch(ext, html = "&#127760;", xlsx = "&#128202;", csv = "&#128202;", net = "&#128376;", "&#128196;")
          items <- c(items, sprintf('<a class="asset file" href="%s" target="_blank">%s&nbsp;%s</a>', rel, ico, esc(f)))
        }
      }
      blocks <- c(blocks, sprintf('<div class="combo"><h4>%s</h4><div class="assets">%s</div></div>', esc(cb), paste(items, collapse = "\n")))
    }
    if (!length(blocks)) return(NULL)
    paste(blocks, collapse = "\n")
  }

  GROUPS <- c("1_search", "2_appraisal", "3_analysis", "4_synthesis")
  GLAB   <- c("1_search" = "1 | Search", "2_appraisal" = "2 | Appraisal",
              "3_analysis" = "3 | Analysis", "4_synthesis" = "4 | Synthesis")

  n_scen <- 0L
  records <- list()
  for (id in ran_ids) {
    sd <- if (id %in% names(scaffold)) scaffold[[id]] else NA_character_
    h  <- humanize(id)
    rh <- results_html(id)
    n_scen <- n_scen + length(list.dirs(file.path(run_dir, id), recursive = FALSE))
    if (is.na(sd)) {                                   # executed but no scaffold match
      records[[length(records) + 1L]] <- list(group = "4_synthesis", id = id, num = h$num, title = h$title,
                                              key = sortkey(h$num), path = id,
                                              tabs = list(list(name = "Results", html = rh)))
      next
    }
    relp  <- sub(paste0("^", fwd(base), "/"), "", fwd(sd)); group <- strsplit(relp, "/")[[1]][1]
    mfo <- file.path(sd, "metadata_ui", "info_and_reference", "info_referencias.md")
    mop <- file.path(sd, "metadata_ui", "options", "options.md")
    mtb <- file.path(sd, "metadata_ui", "tabs", "tabs.md")
    tabs <- list()
    if (file.exists(mfo)) tabs[[length(tabs) + 1L]] <- list(name = "Info &amp; References", html = md2html(mfo))
    tabs[[length(tabs) + 1L]] <- list(name = "Options", html = md2html(mop))
    tabs[[length(tabs) + 1L]] <- list(name = "Tabs",    html = md2html(mtb))
    if (!is.null(rh)) tabs[[length(tabs) + 1L]] <- list(name = "Results", html = rh)
    records[[length(records) + 1L]] <- list(group = group, id = id, num = h$num, title = h$title,
                                            key = sortkey(h$num), path = relp, tabs = tabs)
  }
  gord <- match(vapply(records, `[[`, "", "group"), GROUPS); gord[is.na(gord)] <- 99L
  records <- records[order(gord, vapply(records, `[[`, "", "key"))]

  # --- run header info --------------------------------------------------------
  ndocs <- timespan <- nsrc <- NA
  ci <- file.path(run_dir, "_corpus_info.json")
  if (file.exists(ci) && requireNamespace("jsonlite", quietly = TRUE)) {
    info <- tryCatch(jsonlite::read_json(ci), error = function(e) NULL)
    if (!is.null(info)) { ndocs <- info$n_documents; timespan <- info$timespan; nsrc <- info$sources }
  }
  corpus_line <- if (!is.na(ndocs)) sprintf("%s docs | %s | %s fuentes", ndocs, timespan, nsrc) else "corpus n/d"

  # --- assemble nav + panels --------------------------------------------------
  nav <- character(0); pan <- character(0); last_group <- ""
  for (i in seq_along(records)) {
    r <- records[[i]]; idx <- i - 1L
    if (r$group != last_group) {
      if (last_group != "") nav <- c(nav, "</div>")
      glab <- if (r$group %in% names(GLAB)) GLAB[[r$group]] else r$group
      nav <- c(nav, sprintf('<div class="nav-group"><div class="nav-group-title">%s</div>', esc(glab)))
      last_group <- r$group
    }
    nav <- c(nav, sprintf('<a class="nav-item" id="nav-%d" data-name="%s" onclick="selSec(%d)"><span class="badge">%s</span>%s</a>',
                          idx, esc(tolower(paste(r$num, r$title))), idx, esc(r$num), esc(r$title)))
    tb <- character(0); tc <- character(0)
    for (j in seq_along(r$tabs)) {
      t <- r$tabs[[j]]
      tb <- c(tb, sprintf('<button class="tab-btn" onclick="selTab(%d,%d)">%s</button>', idx, j - 1L, t$name))
      body <- if (is.null(t$html)) '<p class="empty">- sin contenido -</p>' else t$html
      tc <- c(tc, sprintf('<div class="tab-pane" id="tc-%d-%d">%s</div>', idx, j - 1L, body))
    }
    pan <- c(pan, sprintf(
      '<section class="section-panel" id="sec-%d"><div class="sec-head"><h2><span class="badge big">%s</span>%s</h2><div class="crumb">%s</div></div><div class="tabbar">%s</div>%s</section>',
      idx, esc(r$num), esc(r$title), esc(r$path), paste(tb, collapse = ""), paste(tc, collapse = "\n")))
  }
  if (last_group != "") nav <- c(nav, "</div>")

  css <- '
:root{--bg:#f6f7f9;--panel:#fff;--ink:#1f2430;--muted:#6b7280;--line:#e5e7eb;--brand:#2563eb;--brand2:#1e40af;--badge:#eef2ff}
*{box-sizing:border-box}
body{margin:0;font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:var(--ink);background:var(--bg)}
.app{display:flex;min-height:100vh}
.side{width:330px;flex:none;background:var(--panel);border-right:1px solid var(--line);height:100vh;position:sticky;top:0;overflow:auto}
.side h1{font-size:15px;margin:0;padding:16px 16px 4px}
.side .sub{font-size:12px;color:var(--muted);padding:0 16px 4px}
.side .sub code{font-size:11px}
.search{margin:8px 12px 12px;width:calc(100% - 24px);padding:8px 10px;border:1px solid var(--line);border-radius:8px;font-size:13px}
.nav-group{padding:2px 0 6px}
.nav-group-title{font-size:11px;letter-spacing:.06em;text-transform:uppercase;color:var(--muted);padding:10px 16px 4px;font-weight:600}
.nav-item{display:flex;gap:8px;align-items:baseline;padding:6px 16px;cursor:pointer;font-size:13px;color:var(--ink);text-decoration:none;border-left:3px solid transparent}
.nav-item:hover{background:#f0f4ff}
.nav-item.active{background:var(--badge);border-left-color:var(--brand);font-weight:600}
.badge{font:600 11px/1 ui-monospace,Menlo,Consolas,monospace;color:var(--brand2);background:var(--badge);padding:3px 6px;border-radius:6px;white-space:nowrap}
.badge.big{font-size:13px;margin-right:10px}
.main{flex:1;min-width:0;padding:26px 34px 80px;max-width:1100px}
.section-panel{display:none}
.section-panel.active{display:block}
.sec-head h2{display:flex;align-items:center;margin:0 0 2px;font-size:22px}
.crumb{font:12px ui-monospace,Menlo,Consolas,monospace;color:var(--muted);margin-bottom:16px}
.tabbar{display:flex;gap:4px;flex-wrap:wrap;border-bottom:2px solid var(--line);margin-bottom:18px}
.tab-btn{border:none;background:none;padding:9px 14px;cursor:pointer;font-size:13px;color:var(--muted);border-bottom:2px solid transparent;margin-bottom:-2px}
.tab-btn:hover{color:var(--ink)}
.tab-btn.active{color:var(--brand);border-bottom-color:var(--brand);font-weight:600}
.tab-pane{display:none}
.tab-pane.active{display:block}
.tab-pane h1{font-size:20px}.tab-pane h2{font-size:17px;border-bottom:1px solid var(--line);padding-bottom:4px;margin-top:26px}
.tab-pane h3{font-size:15px}.tab-pane h4{font-size:13px;color:var(--muted)}
.tab-pane table{border-collapse:collapse;width:100%;margin:12px 0;font-size:13px;display:block;overflow-x:auto}
.tab-pane th,.tab-pane td{border:1px solid var(--line);padding:6px 9px;text-align:left;vertical-align:top}
.tab-pane th{background:#f3f4f6;font-weight:600}
.tab-pane tr:nth-child(even) td{background:#fafbfc}
.tab-pane code{background:#f1f3f5;padding:1px 5px;border-radius:4px;font:12.5px ui-monospace,Menlo,Consolas,monospace}
.tab-pane pre{background:#0f172a;color:#e2e8f0;padding:12px 14px;border-radius:8px;overflow:auto}
.tab-pane pre code{background:none;color:inherit;padding:0}
.tab-pane blockquote{border-left:3px solid var(--brand);margin:12px 0;padding:2px 14px;color:var(--muted);background:#f8faff}
.empty{color:var(--muted);font-style:italic}
.combo{margin:14px 0 22px}.combo h4{font:600 13px ui-monospace,Menlo,Consolas,monospace;color:var(--brand2);margin:0 0 8px}
.assets{display:flex;flex-wrap:wrap;gap:14px;align-items:flex-start}
.asset img{max-width:340px;max-height:300px;border:1px solid var(--line);border-radius:8px;background:#fff;display:block}
figure.asset{margin:0}figure.asset figcaption{font:11px ui-monospace,Menlo,Consolas,monospace;color:var(--muted);max-width:340px;word-break:break-all;margin-top:4px}
a.asset.file{display:inline-block;padding:9px 12px;border:1px solid var(--line);border-radius:8px;background:#fff;font:12px ui-monospace,Menlo,Consolas,monospace;text-decoration:none;color:var(--brand2);word-break:break-all;max-width:360px}
a.asset.file:hover{border-color:var(--brand);background:#f0f4ff}
'

  js <- "
function selSec(i){
  document.querySelectorAll('.section-panel').forEach(function(s){s.classList.remove('active')});
  document.querySelectorAll('.nav-item').forEach(function(n){n.classList.remove('active')});
  document.getElementById('sec-'+i).classList.add('active');
  document.getElementById('nav-'+i).classList.add('active');
  selTab(i,0); location.hash=i; window.scrollTo(0,0);
}
function selTab(i,j){
  var sec=document.getElementById('sec-'+i);
  sec.querySelectorAll('.tab-btn').forEach(function(b){b.classList.remove('active')});
  sec.querySelectorAll('.tab-pane').forEach(function(p){p.classList.remove('active')});
  sec.querySelectorAll('.tab-btn')[j].classList.add('active');
  var pane=document.getElementById('tc-'+i+'-'+j); if(pane) pane.classList.add('active');
}
function filterNav(q){
  q=q.toLowerCase();
  document.querySelectorAll('.nav-item').forEach(function(n){ n.style.display = n.dataset.name.indexOf(q)>=0 ? '' : 'none'; });
}
window.addEventListener('DOMContentLoaded',function(){ var h=parseInt(location.hash.replace('#','')); selSec(isNaN(h)?0:h); });
"

  html <- paste0(
    '<!doctype html><html lang="es"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>Run ', esc(run_ts), ' - biblioshiny</title><style>', css, '</style></head><body>',
    '<div class="app"><aside class="side">',
    '<h1>Resultados del run</h1>',
    '<div class="sub"><code>', esc(run_ts), '</code></div>',
    '<div class="sub">', length(records), ' secciones | ', n_scen, ' escenarios</div>',
    '<div class="sub">', esc(corpus_line), '</div>',
    '<input class="search" placeholder="Filtrar secciones&hellip;" oninput="filterNav(this.value)">',
    paste(nav, collapse = "\n"),
    '</aside><main class="main">',
    paste(pan, collapse = "\n"),
    '</main></div><script>', js, '</script></body></html>')

  out <- file.path(run_dir, "index.html")
  con <- file(out, "w", encoding = "UTF-8"); writeLines(html, con); close(con)
  message(sprintf("[index] wrote %s (%d executed sections, %d scenarios)", out, length(records), n_scen))
  invisible(out)
}

#' (Re)build the self-contained HTML viewer for a run
#'
#' The viewer is written automatically at the end of [cbe_run()]; use this to
#' regenerate it for an existing run (e.g. after upgrading the package).
#'
#' @param run_dir Path to a run directory produced by [cbe_run()].
#' @return (invisibly) the path to the written `index.html`.
#' @export
cbe_build_index <- function(run_dir) build_run_index(run_dir, basename(run_dir))

